import React from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, ClipboardList, CheckCircle2, AlertTriangle } from 'lucide-react'

import { PageShell, PageHeader, Footnote } from '@/components/common/Layout'
import { ChartPanel } from '@/components/analytics/ChartPanel'
import { RiskGauge } from '@/components/risk/RiskGauge'
import { RiskBadge } from '@/components/risk/RiskBadge'
import { SignalBars } from '@/components/risk/SignalBars'
import { ApplicantSummary } from '@/components/assessment/ApplicantSummary'
import { EmptyState } from '@/components/common/States'
import { buttonVariants } from '@/components/common/Button'
import { useAssessment } from '@/context/AssessmentContext'
import { featureImportance } from '@/lib/reference-data'
import { cn } from '@/lib/utils'

export default function RiskAnalysisPage() {
  const { result, applicant } = useAssessment()

  if (!result) {
    return (
      <div className="pb-24">
        <PageShell>
          <PageHeader
            eyebrow="Risk Analysis"
            title="No assessment yet"
            description="Run an applicant through the assessment workflow to see a detailed risk breakdown here."
          />
          <div className="py-12">
            <EmptyState
              icon={<ClipboardList className="size-5" />}
              title="No assessment to display"
              description="Complete the five-step assessment workflow to generate a default-probability analysis for an applicant."
              action={
                <Link to="/assess" className={buttonVariants({ variant: 'default', size: 'lg' })}>
                  Start an assessment
                  <ArrowRight className="size-4" data-icon="inline-end" />
                </Link>
              }
            />
          </div>
        </PageShell>
      </div>
    )
  }

  const predictedTime = new Date(result.predictedAt).toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  const isDefault = result.classification === 'DEFAULT'

  return (
    <div className="pb-24">
      <PageShell>
        <PageHeader
          eyebrow="Risk Analysis"
          title="Default probability assessment"
          description="Live machine-learning classification generated by the production HistGradientBoosting pipeline."
          actions={
            <Link to="/assess" className={buttonVariants({ variant: 'outline', size: 'lg' })}>
              New assessment
            </Link>
          }
        />

        {/* Centerpiece */}
        <div className="grid gap-5 py-8 lg:grid-cols-[0.9fr_1.1fr]">
          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
            className="flex flex-col items-center justify-center rounded-xl border border-hairline bg-surface p-8 text-center"
          >
            <RiskGauge probability={result.probability} />

            <div className="mt-6 flex flex-col items-center gap-3">
              <div>
                <p className="label-eyebrow">Predicted Classification</p>
                <p
                  className={cn(
                    'mt-1 text-2xl font-semibold tracking-tight',
                    isDefault ? 'text-danger' : 'text-teal',
                  )}
                >
                  {result.classification}
                </p>
              </div>

              <div className="flex items-center gap-2">
                <RiskBadge band={result.band} size="lg" />
                <span className="text-xs text-muted-ink">
                  ({result.riskLevel})
                </span>
              </div>

              <div className="mt-2 max-w-sm rounded-lg border border-hairline bg-secondary/50 p-3 text-xs leading-relaxed text-muted-ink">
                {result.message}
              </div>
            </div>
          </motion.div>

          <div className="grid gap-5">
            {/* Prediction-Specific Signals */}
            <ChartPanel
              title="Applicant risk factors"
              eyebrow="Prediction-Specific Explanation"
              description="Primary factors identified for this specific applicant profile during model inference."
            >
              <ul className="divide-y divide-hairline">
                {result.riskFactors && result.riskFactors.length > 0 ? (
                  result.riskFactors.map((factor, i) => (
                    <li key={i} className="flex items-start gap-3 py-2.5 text-sm text-ink first:pt-0 last:pb-0">
                      {isDefault ? (
                        <AlertTriangle className="mt-0.5 size-4 shrink-0 text-danger" />
                      ) : (
                        <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-teal" />
                      )}
                      <span>{factor}</span>
                    </li>
                  ))
                ) : (
                  <li className="py-2 text-sm text-muted-ink">
                    No elevated risk factors detected.
                  </li>
                )}
              </ul>
            </ChartPanel>

            {/* Global Feature Importance */}
            <ChartPanel
              title="Global feature importance"
              eyebrow="Portfolio Model Signals"
              description="Portfolio-wide permutation feature importance across 255,347 loans. Ranks aggregate model reliance."
            >
              {(() => {
                const maxImp = featureImportance[0]?.importance || 1
                return (
                  <SignalBars
                    items={featureImportance.slice(0, 5).map((f) => ({
                      label: f.feature,
                      weight: f.importance / maxImp,
                      value: `${(f.importance * 100).toFixed(1)}%`,
                    }))}
                  />
                )
              })()}
              <p className="mt-3 text-[11px] text-muted-ink">
                Note: Global feature importance reflects portfolio-wide feature sensitivity and provides architectural context alongside individual applicant factors.
              </p>
            </ChartPanel>

            {/* Assessment Metadata */}
            <ChartPanel title="Assessment metadata" eyebrow="Provenance">
              <dl className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                <MetaItem label="Model" value={result.model} />
                <MetaItem label="Version" value={result.modelVersion} />
                <MetaItem label="Prediction time" value={predictedTime} />
                <MetaItem label="Decision Threshold" value="0.500" />
              </dl>
            </ChartPanel>
          </div>
        </div>

        {/* Applicant summary */}
        <section className="py-4">
          <div className="mb-5 flex items-end justify-between">
            <div>
              <p className="label-eyebrow mb-1.5">Applicant Summary</p>
              <h2 className="text-xl font-semibold tracking-tight text-ink">Submitted information</h2>
            </div>
            <Link to="/assess" className="text-sm font-medium text-brand-accent hover:underline">
              Edit applicant
            </Link>
          </div>
          <ApplicantSummary applicant={applicant} columns={4} />
        </section>

        <Footnote className="mt-6">
          Prediction generated using the trained HistGradientBoostingClassifier pipeline evaluated on the loan default benchmark portfolio. All model scores indicate statistical probability and underwriting decision assistance.
        </Footnote>
      </PageShell>
    </div>
  )
}

function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-1">
      <dt className="label-eyebrow">{label}</dt>
      <dd className="text-sm font-medium text-ink">{value}</dd>
    </div>
  )
}
